# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: simplifyd
email: simplifydpodcast@gmail.com
description:  Simplifying academic research.
url: "https://github.com/gsidhu/simplifyd" # the base hostname & protocol for your site
twitter_username: simplifydcast
github_username: gsidhu
repo: https://github.com/gsidhu/simplifyd
comments: true
permalink: /blog/:title
future: true
gems:
  - jekyll-redirect-from
# Build settings
markdown: kramdown
highlighter: rouge
