# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: simplifyd
email: Making academia accessible
description:  We are still under construction. You'll know when we go live.
url: "http://simplifyd.xyz" # the base hostname & protocol for your site
twitter_username: simplifydcast
github_username: gsidhu
repo: https://github.com/gsidhu/simplifyd
comments: true
permalink: /blog/:title

# Build settings
markdown: kramdown
highlighter: rouge
